@extends('navbar')

@section('content')

</p>SELAMAT DATANG DI PROFIL SAYA </P>
</P>NAMA : TENDI ROY </P>
</P>TEMPAT/TANGGAL LAHIR : BANDUNG,7 JANUARI 2004 </P>
</P>ALAMAT : GRAHA RANCAMANYAR,JL.ROSE NO.41</P> 